from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1118, 846)
        self.background = QtWidgets.QLabel(Dialog)
        self.background.setGeometry(QtCore.QRect(-320, -140, 1911, 1071))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.background.setFont(font)
        self.background.setStyleSheet("background-color:black\n"
"")
        self.background.setText("")
        self.background.setObjectName("background")
        self.cornerironman = QtWidgets.QLabel(Dialog)
        self.cornerironman.setGeometry(QtCore.QRect(760, 10, 431, 401))
        self.cornerironman.setText("")
        self.cornerironman.setPixmap(QtGui.QPixmap("C:/Users/prasa/PycharmProjects/pythonProject/GUI/ironman.jpg"))
        self.cornerironman.setScaledContents(True)
        self.cornerironman.setObjectName("cornerironman")
        self.stop = QtWidgets.QLabel(Dialog)
        self.stop.setGeometry(QtCore.QRect(820, 670, 241, 141))
        self.stop.setText("")
        self.stop.setPixmap(QtGui.QPixmap("C:/Users/prasa/PycharmProjects/pythonProject/GUI/stops.jpg"))
        self.stop.setScaledContents(True)
        self.stop.setObjectName("stop")
        self.start = QtWidgets.QLabel(Dialog)
        self.start.setGeometry(QtCore.QRect(20, 650, 261, 181))
        self.start.setText("")
        self.start.setPixmap(QtGui.QPixmap("C:/Users/prasa/PycharmProjects/pythonProject/GUI/starts.jpg"))
        self.start.setScaledContents(True)
        self.start.setObjectName("start")
        self.coding = QtWidgets.QLabel(Dialog)
        self.coding.setGeometry(QtCore.QRect(10, 40, 361, 341))
        self.coding.setText("")
        self.coding.setPixmap(QtGui.QPixmap("C:/Users/prasa/PycharmProjects/pythonProject/GUI/download.gif"))
        self.coding.setScaledContents(True)
        self.coding.setObjectName("coding")
        self.date = QtWidgets.QLabel(Dialog)
        self.date.setGeometry(QtCore.QRect(14, 495, 261, 131))
        self.date.setText("")
        self.date.setPixmap(QtGui.QPixmap("C:/Users/prasa/PycharmProjects/pythonProject/GUI/date.jpg"))
        self.date.setScaledContents(True)
        self.date.setObjectName("date")
        self.time = QtWidgets.QLabel(Dialog)
        self.time.setGeometry(QtCore.QRect(810, 490, 261, 131))
        self.time.setText("")
        self.time.setPixmap(QtGui.QPixmap("C:/Users/prasa/PycharmProjects/pythonProject/GUI/date.jpg"))
        self.time.setScaledContents(True)
        self.time.setObjectName("time")
        self.startbutton = QtWidgets.QPushButton(Dialog)
        self.startbutton.setGeometry(QtCore.QRect(42, 680, 211, 121))
        self.startbutton.setStyleSheet("background-color:transparent;")
        self.startbutton.setText("")
        self.startbutton.setObjectName("startbutton")
        self.stopbutton = QtWidgets.QPushButton(Dialog)
        self.stopbutton.setGeometry(QtCore.QRect(840, 680, 211, 121))
        self.stopbutton.setStyleSheet("background-color:transparent;")
        self.stopbutton.setText("")
        self.stopbutton.setObjectName("stopbutton")
        self.datebutton = QtWidgets.QTextBrowser(Dialog)
        self.datebutton.setGeometry(QtCore.QRect(60, 530, 171, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datebutton.sizePolicy().hasHeightForWidth())
        self.datebutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.datebutton.setFont(font)
        self.datebutton.setStyleSheet("background-color:skyblue;")
        self.datebutton.setObjectName("datebutton")
        self.timebutton = QtWidgets.QTextBrowser(Dialog)
        self.timebutton.setGeometry(QtCore.QRect(860, 520, 171, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timebutton.sizePolicy().hasHeightForWidth())
        self.timebutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.timebutton.setFont(font)
        self.timebutton.setStyleSheet("background-color:skyblue;")
        self.timebutton.setObjectName("timebutton")
        self.jarvis = QtWidgets.QLabel(Dialog)
        self.jarvis.setGeometry(QtCore.QRect(270, 70, 611, 351))
        self.jarvis.setText("")
        self.jarvis.setPixmap(QtGui.QPixmap("C:/Users/prasa/PycharmProjects/pythonProject/GUI/jarvis.gif"))
        self.jarvis.setScaledContents(True)
        self.jarvis.setObjectName("jarvis")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(309, 500, 481, 321))
        self.frame.setStyleSheet("border: 2px solid white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.terminaloutput = QtWidgets.QPlainTextEdit(self.frame)
        self.terminaloutput.setGeometry(QtCore.QRect(13, 16, 451, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.terminaloutput.setFont(font)
        self.terminaloutput.setObjectName("terminaloutput")
        self.background.raise_()
        self.start.raise_()
        self.date.raise_()
        self.time.raise_()
        self.stop.raise_()
        self.startbutton.raise_()
        self.stopbutton.raise_()
        self.datebutton.raise_()
        self.timebutton.raise_()
        self.jarvis.raise_()
        self.cornerironman.raise_()
        self.coding.raise_()
        self.frame.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.datebutton.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Date:01-01-2025</span></p></body></html>"))
        self.timebutton.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Time:12:00:00</span></p></body></html>"))
        self.terminaloutput.setPlainText(_translate("Dialog", "Lisenting...\n"
""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())